flags:
    SciFlow:
        sge: True
        debug: True

packages:
    - '.'
    - ../bio-experiments
    - ../SciFlow
    - ../bioinformatics-toolkit

extra-deps:
    - drmaa-0.1.0.1
    - samtools-0.2.4.3

resolver: lts-6.1
